// PMP 6th edition process catalogue. ITTO terms are transcribed from the supplied
// project-management notes and kept as structured arrays for use by the UI.
const item = (id, area, group, en, zh, inputs, tools, outputs, purpose) => ({
  id, area, group, name: { en, zh }, purpose: { en: purpose, zh: purpose },
  itto: { inputs, tools, outputs }
});

const common = {
  charter: 'Project charter', plan: 'Project management plan', docs: 'Project documents',
  eef: 'Enterprise environmental factors', opa: 'Organizational process assets',
  expert: 'Expert judgment', meeting: 'Meetings', data: 'Data analysis'
};
const c = common;

export const PMP_PROCESSES = [
  item('4.1','integration','initiating','Develop Project Charter','制定项目章程',['Business documents (business case, benefits management plan)','Agreements',c.eef,c.opa],[c.expert,'Data gathering (brainstorming, focus groups, interviews)','Interpersonal and team skills','Meetings'],['Project charter','Assumption log'],'Formally authorizes the project and gives the project manager authority.'),
  item('4.2','integration','planning','Develop Project Management Plan','制定项目管理计划',[c.charter,'Outputs from other processes',c.eef,c.opa],[c.expert,'Data gathering','Interpersonal and team skills','Meetings'],[c.plan],'Defines how the project will be executed, monitored, controlled, and closed.'),
  item('4.3','integration','executing','Direct and Manage Project Work','指导与管理项目工作',[c.plan,c.docs,'Approved change requests',c.eef,c.opa],[c.expert,'Project management information system','Meetings'],['Deliverables','Work performance data','Issue log','Change requests','Project management plan updates','Project document updates','Organizational process assets updates'],'Leads the work needed to produce project deliverables.'),
  item('4.4','integration','executing','Manage Project Knowledge','管理项目知识',[c.plan,c.docs,'Deliverables',c.eef,c.opa],[c.expert,'Knowledge management','Information management','Interpersonal and team skills'],['Lessons learned register','Project management plan updates','Organizational process assets updates'],'Uses existing knowledge and creates new knowledge to meet objectives.'),
  item('4.5','integration','monitoring','Monitor and Control Project Work','监控项目工作',[c.plan,c.docs,'Work performance information','Agreements',c.eef,c.opa],[c.expert,c.data,'Decision making','Meetings'],['Work performance reports','Change requests','Project management plan updates','Project document updates'],'Tracks, reviews, and reports overall progress.'),
  item('4.6','integration','monitoring','Perform Integrated Change Control','实施整体变更控制',[c.plan,c.docs,'Work performance reports','Change requests',c.eef,c.opa],[c.expert,'Change control tools','Data analysis','Decision making','Meetings'],['Approved change requests','Project management plan updates','Project document updates'],'Reviews all change requests and manages approved changes.'),
  item('4.7','integration','closing','Close Project or Phase','结束项目或阶段',[c.charter,c.plan,c.docs,'Accepted deliverables','Business documents','Agreements',c.opa],[c.expert,c.data,'Meetings'],['Project documents updates','Final product, service, or result transition report','Final report','Organizational process assets updates'],'Finalizes all activities and formally closes the project or phase.'),
  item('5.1','scope','planning','Plan Scope Management','规划范围管理',[c.charter,c.plan,c.eef,c.opa],[c.expert,c.data,'Meetings'],['Scope management plan','Requirements management plan'],'Defines how scope and requirements are defined, validated, and controlled.'),
  item('5.2','scope','planning','Collect Requirements','收集需求',[c.charter,c.plan,c.docs,'Business documents','Agreements',c.eef,c.opa],[c.expert,'Data gathering','Data analysis','Decision making','Data representation','Interpersonal and team skills','Prototypes'],['Requirements documentation','Requirements traceability matrix'],'Determines and documents stakeholder needs and requirements.'),
  item('5.3','scope','planning','Define Scope','定义范围',[c.charter,c.plan,c.docs,c.eef,c.opa],[c.expert,c.data,'Decision making','Interpersonal and team skills','Product analysis'],['Project scope statement','Project documents updates'],'Develops the detailed description of the project and product.'),
  item('5.4','scope','planning','Create WBS','创建工作分解结构',[c.plan,c.docs],[c.expert,'Decomposition'],['Scope baseline','Project documents updates'],'Subdivides deliverables and work into manageable components.'),
  item('5.5','scope','monitoring','Validate Scope','确认范围',[c.plan,c.docs,'Verified deliverables','Work performance data'],['Inspection','Decision making'],['Accepted deliverables','Work performance information','Change requests','Project documents updates'],'Formalizes acceptance of completed deliverables.'),
  item('5.6','scope','monitoring','Control Scope','控制范围',[c.plan,c.docs,'Work performance data'],[c.data],['Work performance information','Change requests','Project management plan updates','Project documents updates'],'Monitors scope status and manages changes to the scope baseline.'),
  item('6.1','schedule','planning','Plan Schedule Management','规划进度管理',[c.charter,c.plan,c.eef,c.opa],[c.expert,c.data,'Meetings'],['Schedule management plan'],'Establishes how the schedule will be developed and controlled.'),
  item('6.2','schedule','planning','Define Activities','定义活动',[c.plan,c.eef,c.opa],[c.expert,'Decomposition','Rolling wave planning','Meetings'],['Activity list','Activity attributes','Milestone list','Change requests','Project management plan updates'],'Identifies specific activities needed to produce deliverables.'),
  item('6.3','schedule','planning','Sequence Activities','排列活动顺序',[c.plan,c.docs,c.eef,c.opa],['Precedence diagramming method','Dependency determination and integration','Leads and lags'],['Project schedule network diagrams','Project documents updates'],'Identifies and documents logical relationships among activities.'),
  item('6.4','schedule','planning','Estimate Activity Durations','估算活动持续时间',[c.plan,c.docs,c.eef,c.opa],[c.expert,'Analogous estimating','Parametric estimating','Three-point estimating','Bottom-up estimating',c.data,'Decision making'],['Duration estimates','Basis of estimates','Project documents updates'],'Estimates the number of work periods needed for activities.'),
  item('6.5','schedule','planning','Develop Schedule','制定进度计划',[c.plan,c.docs,'Agreements',c.eef,c.opa],[c.expert,'Schedule network analysis','Critical path method','Resource optimization','Data analysis','Leads and lags','Schedule compression','Project management information system','Agile releases planning'],['Schedule baseline','Project schedule','Schedule data','Project calendars','Change requests','Project management plan updates','Project documents updates'],'Creates the approved model for execution and control.'),
  item('6.6','schedule','monitoring','Control Schedule','控制进度',[c.plan,c.docs,'Work performance data',c.opa],[c.data,'Critical path method','Project management information system','Resource optimization','Leads and lags','Schedule compression'],['Work performance information','Schedule forecasts','Change requests','Project management plan updates','Project documents updates'],'Monitors schedule status and manages schedule baseline changes.'),
  item('7.1','cost','planning','Plan Cost Management','规划成本管理',[c.charter,c.plan,c.eef,c.opa],[c.expert,c.data,'Meetings'],['Cost management plan'],'Defines how costs will be estimated, budgeted, managed, monitored, and controlled.'),
  item('7.2','cost','planning','Estimate Costs','估算成本',[c.plan,c.docs,c.eef,c.opa],[c.expert,'Analogous estimating','Parametric estimating','Bottom-up estimating','Three-point estimating',c.data,'Project management information system','Decision making'],['Cost estimates','Basis of estimates','Project documents updates'],'Develops an approximation of monetary resources needed.'),
  item('7.3','cost','planning','Determine Budget','制定预算',[c.plan,c.docs,'Business documents','Agreements',c.eef,c.opa],[c.expert,'Cost aggregation',c.data,'Historical information review','Funding limit reconciliation','Financing'],['Cost baseline','Project funding requirements','Project documents updates'],'Aggregates estimated costs into an authorized cost baseline.'),
  item('7.4','cost','monitoring','Control Costs','控制成本',[c.plan,c.docs,'Project funding requirements','Work performance data',c.opa],[c.expert,'Earned value analysis','Variance analysis','Trend analysis','Reserve analysis','To-complete performance index','Project management information system'],['Work performance information','Cost forecasts','Change requests','Project management plan updates','Project documents updates'],'Monitors project status and manages changes to the cost baseline.'),
  item('8.1','quality','planning','Plan Quality Management','规划质量管理',[c.charter,c.plan,c.docs,c.eef,c.opa],[c.expert,'Data gathering','Data analysis','Decision making','Data representation','Test and inspection planning','Meetings'],['Quality management plan','Quality metrics','Project management plan updates','Project documents updates'],'Identifies quality requirements and standards and how compliance will be demonstrated.'),
  item('8.2','quality','executing','Manage Quality','管理质量',[c.plan,c.docs,c.opa],[c.data,'Data representation','Audits','Design for X','Problem solving','Quality improvement methods'],['Quality reports','Test and evaluation documents','Change requests','Project management plan updates','Project documents updates'],'Turns the quality plan into auditable quality assurance activities.'),
  item('8.3','quality','monitoring','Control Quality','控制质量',[c.plan,c.docs,'Approved change requests','Deliverables','Work performance data',c.eef,c.opa],['Data gathering','Data analysis','Inspection','Testing or product evaluations','Data representation','Meetings'],['Quality control measurements','Verified deliverables','Work performance information','Change requests','Project management plan updates','Project documents updates'],'Verifies deliverables and measures quality performance.'),
  item('9.1','resource','planning','Plan Resource Management','规划资源管理',[c.charter,c.plan,c.docs,c.eef,c.opa],[c.expert,'Data representation','Organizational theory','Meetings'],['Resource management plan','Team charter','Project documents updates'],'Defines how team and physical resources are estimated, acquired, and managed.'),
  item('9.2','resource','planning','Estimate Activity Resources','估算活动资源',[c.plan,c.docs,c.eef,c.opa],[c.expert,'Bottom-up estimating','Analogous estimating','Parametric estimating',c.data,'Project management information system','Meetings'],['Resource requirements','Basis of estimates','Resource breakdown structure','Project documents updates'],'Estimates team, material, equipment, and supplies needed for work.'),
  item('9.3','resource','executing','Acquire Resources','获取资源',[c.plan,c.docs,c.eef,c.opa],['Decision making','Interpersonal and team skills','Pre-assignment','Virtual teams'],['Physical resource assignments','Project team assignments','Resource calendars','Change requests','Project management plan updates','Project documents updates',c.eef,c.opa],'Obtains team members and physical resources for the project.'),
  item('9.4','resource','executing','Develop Team','建设团队',[c.plan,c.docs,c.eef,c.opa],['Colocation','Virtual teams','Communication technology','Interpersonal and team skills','Recognition and rewards','Training','Individual and team assessments','Meetings'],['Team performance assessments','Change requests','Project management plan updates','Project documents updates',c.eef,c.opa],'Improves competencies, interaction, and team environment.'),
  item('9.5','resource','executing','Manage Team','管理团队',[c.plan,c.docs,'Work performance reports','Team performance assessments',c.eef,c.opa],['Interpersonal and team skills','Project management information system'],['Change requests','Project management plan updates','Project documents updates',c.eef,c.opa],'Tracks performance, resolves issues, and manages team changes.'),
  item('9.6','resource','monitoring','Control Resources','控制资源',[c.plan,c.docs,'Work performance data','Agreements',c.opa],[c.data,'Problem solving','Interpersonal and team skills','Project management information system'],['Work performance information','Change requests','Project management plan updates','Project documents updates'],'Ensures assigned physical resources are available and used as planned.'),
  item('10.1','communications','planning','Plan Communications Management','规划沟通管理',[c.charter,c.plan,c.docs,c.eef,c.opa],[c.expert,'Communication requirements analysis','Communication technology','Communication models','Communication methods','Interpersonal and team skills','Data representation','Meetings'],['Communications management plan','Project management plan updates','Project documents updates'],'Develops a timely and effective communications approach.'),
  item('10.2','communications','executing','Manage Communications','管理沟通',[c.plan,c.docs,'Work performance reports',c.eef,c.opa],['Communication technology','Communication methods','Communication skills','Project management information system','Project reporting','Interpersonal and team skills'],['Project communications','Project management plan updates','Project documents updates',c.opa],'Ensures information is collected, created, distributed, stored, and retrieved.'),
  item('10.3','communications','monitoring','Monitor Communications','监督沟通',[c.plan,c.docs,'Work performance data',c.eef,c.opa],[c.expert,'Project management information system','Data representation','Interpersonal and team skills','Meetings'],['Work performance information','Change requests','Project management plan updates','Project documents updates'],'Ensures stakeholder communication needs are met.'),
  item('11.1','risk','planning','Plan Risk Management','规划风险管理',[c.charter,c.plan,c.docs,c.eef,c.opa],[c.expert,c.data,'Meetings'],['Risk management plan'],'Defines how risk management activities will be conducted.'),
  item('11.2','risk','planning','Identify Risks','识别风险',[c.plan,c.docs,'Procurement documents','Agreements',c.eef,c.opa],[c.expert,'Data gathering','Data analysis','Interpersonal and team skills','Prompt lists','Meetings'],['Risk register','Risk report','Project documents updates'],'Identifies individual and overall project risks and their characteristics.'),
  item('11.3','risk','planning','Perform Qualitative Risk Analysis','实施定性风险分析',[c.plan,c.docs,c.eef,c.opa],[c.expert,'Data gathering',c.data,'Interpersonal and team skills','Risk categorization','Data representation','Meetings'],['Project documents updates'],'Prioritizes risks by probability, impact, and other characteristics.'),
  item('11.4','risk','planning','Perform Quantitative Risk Analysis','实施定量风险分析',[c.plan,c.docs,c.eef,c.opa],[c.expert,'Data gathering','Interpersonal and team skills','Representations of uncertainty',c.data],['Project documents updates'],'Numerically analyzes the effect of identified risks on objectives.'),
  item('11.5','risk','planning','Plan Risk Responses','规划风险应对',[c.plan,c.docs,c.eef,c.opa],[c.expert,'Data gathering','Interpersonal and team skills','Strategies for threats','Strategies for opportunities','Contingent response strategies','Overall project risk strategies',c.data,'Decision making'],['Change requests','Project management plan updates','Project documents updates'],'Develops options and actions for threats and opportunities.'),
  item('11.6','risk','executing','Implement Risk Responses','实施风险应对',[c.plan,c.docs,c.opa],[c.expert,'Interpersonal and team skills','Project management information system'],['Change requests','Project documents updates'],'Implements agreed risk response plans.'),
  item('11.7','risk','monitoring','Monitor Risks','监督风险',[c.plan,c.docs,'Work performance data','Work performance reports'],[c.data,'Audits','Meetings'],['Work performance information','Change requests','Project management plan updates','Project documents updates',c.opa],'Monitors response plans, tracks risks, and identifies new risks.'),
  item('12.1','procurement','planning','Plan Procurement Management','规划采购管理',[c.charter,'Business documents',c.plan,c.docs,c.eef,c.opa],[c.expert,'Data gathering',c.data,'Source selection analysis','Meetings'],['Procurement management plan','Procurement strategy','Bid documents','Procurement statement of work','Source selection criteria','Make-or-buy decisions','Independent cost estimates','Change requests','Project documents updates'],'Documents project procurement decisions and identifies potential sellers.'),
  item('12.2','procurement','executing','Conduct Procurements','实施采购',[c.plan,c.docs,'Procurement documents','Seller proposals',c.eef,c.opa],[c.expert,'Advertising','Bidder conferences',c.data,'Interpersonal and team skills'],['Selected sellers','Agreements','Change requests','Project management plan updates','Project documents updates',c.opa],'Obtains seller responses, selects a seller, and awards a contract.'),
  item('12.3','procurement','monitoring','Control Procurements','控制采购',[c.plan,c.docs,'Procurement documents','Agreements','Work performance data','Approved change requests',c.eef,c.opa],[c.expert,'Claims administration',c.data,'Inspection','Audits'],['Closed procurements','Procurement documents updates','Work performance information','Change requests','Project management plan updates','Project documents updates',c.opa],'Manages procurement relationships, performance, and contractual changes.'),
  item('13.1','stakeholder','initiating','Identify Stakeholders','识别干系人',['Business documents',c.charter,c.plan,c.docs,'Agreements',c.eef,c.opa],[c.expert,'Data gathering',c.data,'Data representation','Meetings'],['Stakeholder register','Change requests','Project management plan updates','Project documents updates'],'Identifies people and organizations that affect or are affected by the project.'),
  item('13.2','stakeholder','planning','Plan Stakeholder Engagement','规划干系人参与',[c.charter,c.plan,c.docs,'Agreements',c.eef,c.opa],[c.expert,'Data gathering',c.data,'Decision making','Data representation','Meetings'],['Stakeholder engagement plan'],'Develops appropriate engagement strategies for stakeholders.'),
  item('13.3','stakeholder','executing','Manage Stakeholder Engagement','管理干系人参与',[c.plan,c.docs,c.eef,c.opa],[c.expert,'Communication skills','Interpersonal and team skills','Ground rules','Meetings'],['Change requests','Project management plan updates','Project documents updates'],'Communicates and works with stakeholders to meet needs and resolve issues.'),
  item('13.4','stakeholder','monitoring','Monitor Stakeholder Engagement','监督干系人参与',[c.plan,c.docs,'Work performance data',c.eef,c.opa],[c.data,'Decision making','Data representation','Communication skills','Interpersonal and team skills','Meetings'],['Work performance information','Change requests','Project management plan updates','Project documents updates'],'Monitors stakeholder relationships and adjusts engagement strategies.')
];

export const PROCESS_GROUPS = [
  { key: 'initiating', en: 'Initiating', zh: '启动' },
  { key: 'planning', en: 'Planning', zh: '规划' },
  { key: 'executing', en: 'Executing', zh: '执行' },
  { key: 'monitoring', en: 'Monitoring & Controlling', zh: '监控' },
  { key: 'closing', en: 'Closing', zh: '收尾' }
];

export const KNOWLEDGE_AREAS = [
  ['integration', 'Integration Management', '整合管理'], ['scope', 'Scope Management', '范围管理'],
  ['schedule', 'Schedule Management', '进度管理'], ['cost', 'Cost Management', '成本管理'],
  ['quality', 'Quality Management', '质量管理'], ['resource', 'Resource Management', '资源管理'],
  ['communications', 'Communications Management', '沟通管理'], ['risk', 'Risk Management', '风险管理'],
  ['procurement', 'Procurement Management', '采购管理'], ['stakeholder', 'Stakeholder Management', '干系人管理']
].map(([key, en, zh]) => ({ key, en, zh }));
